hfplatform:
  ingress:
    enabled: true
    className: "nginx"
    annotations: {
      nginx.ingress.kubernetes.io/rewrite-target: /
    }
    hosts:
      - host: config-service.development.local
        paths:
          - path: /
            pathType: Prefix
    tls: [ ]