apiVersion: v2
name: config-service
description: hfplatform - Staging
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
  - name: hfplatform
    version: 1.0.0
    repository: oci://docker.io/jorgebo10
